#!/bin/bash
# CryptoBoss — Marketing & Directory Submission Toolkit
# Updated: July 2026
# 44 MCP tools · Post-paid USDC · Zero signup

HOST="https://cryptoboss.space"

echo ""
echo "  ╔══════════════════════════════════════════════════════════════╗"
echo "  ║        CryptoBoss — Marketing & Directory Blitz             ║"
echo "  ║        44 MCP tools · Post-paid USDC · Zero signup         ║"
echo "  ║        $HOST                 ║"
echo "  ╚══════════════════════════════════════════════════════════════╝"
echo ""

# Health check
echo "▸ Health check..."
curl -sf "$HOST/api/public/market" > /dev/null 2>&1 && echo "  ✓ API live" || echo "  ✗ API NOT REACHABLE!"
curl -sfL "$HOST/" -H "User-Agent: Mozilla/5.0" > /dev/null 2>&1 && echo "  ✓ Website live" || echo "  ✗ Website NOT REACHABLE!"
echo ""

# ─── STATS ───
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  STATS:"
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  • 44 MCP tools across 10 categories"
echo "  • Data: CoinGecko, DeFiLlama, DexScreener, Alternative.me, Etherscan"
echo "  • Payment: Post-paid \$1 USDC on Solana mainnet"
echo "  • Wallet: DEXbxpDbbj5AnZSqfAhuftvjrtXwjoWW1PgrxmVjuZef"
echo "  • Free \$1 credit (~100-200 calls) per API key"
echo "  • Zero signup, zero email, zero subscriptions"
echo "  • Cloudflare Workers — sub-50ms at 330 edge locations"
echo ""

# ─── PING GOOGLE / BING ───
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  PING SEARCH ENGINES:"
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  curl $HOST/ping-search"
echo ""

# ─── MCP CONFIG ───
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  MCP CONFIG — paste into Claude / Cursor / Cline:"
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo '  {"mcpServers":{"cryptoboss":{"type":"streamableHttp","url":"'$HOST'/mcp"}}}'
echo ""

# ─── QUICKSTART ───
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  QUICK START:"
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  curl -X POST $HOST/api/register"
echo '  curl -H "x-api-key: cd_..." '$HOST'/api/price?coins=bitcoin,ethereum'
echo ""

# ─── DIRECTORIES ───
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  SUBMIT TO DIRECTORIES (open each link):"
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo ""
echo "  ┌─ MCP DIRECTORIES ──────────────────────────────────────────┐"
echo "  │  Smithery:        https://smithery.ai/new                  │"
echo "  │  PulseMCP:        https://pulsemcp.com/submit              │"
echo "  │  MCP Central:     https://mcpcentral.io/submit             │"
echo "  │  mcpservers.org:  https://mcpservers.org/submit            │"
echo "  │  AgentNDX:        https://agentndx.ai/submit               │"
echo "  │  mcp.directory:   https://mcp.directory/submit             │"
echo "  │  Glama.ai:        https://glama.ai/mcp/servers             │"
echo "  │  mcpagents.ai:    https://mcpagents.ai/submit              │"
echo "  │  mcp.so:          https://mcp.so/submit                    │"
echo "  │  MCPServerList:   https://mcpserverlist.com/submit         │"
echo "  └────────────────────────────────────────────────────────────┘"
echo ""
echo "  ┌─ API DIRECTORIES ──────────────────────────────────────────┐"
echo "  │  RapidAPI:        https://rapidapi.com/developer/create     │"
echo "  │  APIS.guru:       https://apis.guru/add                    │"
echo "  │  ProgrammableWeb: https://www.programmableweb.com/add-api   │"
echo "  └────────────────────────────────────────────────────────────┘"
echo ""
echo "  ┌─ AI AGENT / CRYPTO DIRECTORIES ───────────────────────────┐"
echo "  │  Heurist Mesh:    https://mesh.heurist.ai/                 │"
echo "  │  AgentStore:      https://agentstore-pi.vercel.app/        │"
echo "  │  AgentRanking:    https://agentranking.io/                 │"
echo "  │  The Spawn:       https://thespawn.io/agents               │"
echo "  │  Agent Index:     https://theagentindex.app/               │"
echo "  │  AIFI Map:        https://aifimap.com/agents               │"
echo "  │  ToolMarket:      https://toolmarket.ai/submit             │"
echo "  └────────────────────────────────────────────────────────────┘"
echo ""
echo "  ┌─ PRODUCT LAUNCH ───────────────────────────────────────────┐"
echo "  │  Product Hunt:  https://www.producthunt.com/posts/new      │"
echo "  │  BetaList:      https://betalist.com/submit                │"
echo "  │  Hacker News:   https://news.ycombinator.com/submit        │"
echo "  └────────────────────────────────────────────────────────────┘"
echo ""
echo "  ┌─ SOCIAL / COMMUNITY ───────────────────────────────────────┐"
echo "  │  Reddit r/cryptodev:  https://reddit.com/r/cryptodev       │"
echo "  │  Reddit r/artificial: https://reddit.com/r/artificial      │"
echo "  │  Reddit r/AI_Agents:  https://reddit.com/r/AI_Agents      │"
echo "  │  Reddit r/Solana:     https://reddit.com/r/Solana         │"
echo "  │  Dev.to:             https://dev.to/new                    │"
echo "  └────────────────────────────────────────────────────────────┘"
echo ""

# ─── SOCIAL POSTS ───
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  SOCIAL POSTS (copy & paste):"
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo ""
echo "── Tweet ──"
echo "Built a crypto API for AI agents."
echo "44 MCP tools. Zero signup. Post-paid \$1 USDC."
echo ""
echo "→ $HOST"
echo "#crypto #MCP #AIagents"
echo ""
echo "── Reddit (r/AI_Agents) ──"
echo "Title: I built 44 free MCP crypto tools for AI agents — post-paid \$1 USDC"
echo ""
echo "Body:"
echo "44 MCP tools across market data, DeFi, meme analysis, security, gas, sentiment."
echo "Zero signup — one click generates a free API key with \$1 credit."
echo "Post-paid billing: send \$1 USDC when credit runs out."
echo ""
echo "MCP auto-discoverable — Claude, Cursor, Cline find it automatically."
echo ""
echo "Web: $HOST"
echo "Register: curl -X POST $HOST/api/register"
echo ""

# ─── SEO ───
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  SEO STATUS:"
echo "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌"
echo "  ✓ robots.txt"
echo "  ✓ sitemap.xml (no hash fragments)"
echo "  ✓ Google Search Console (DNS + meta tag)"
echo "  ✓ OpenGraph + Twitter cards"
echo "  ✓ FAQPage structured data (rich snippets)"
echo "  ✓ WebApplication schema"
echo "  ✓ llms.txt + .well-known/mcp.json"
echo "  ✓ /ping-search endpoint"
echo ""

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Open links above to submit — or run:                       ║"
echo "║  open https://smithery.ai/new                               ║"
echo "║  open https://agentndx.ai/submit                            ║"
echo "║  open https://pulsemcp.com/submit                           ║"
echo "║  open https://glama.ai/mcp/servers                          ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
